dist: focal 

language: python

python:
  - "3.8"

install:
  - pip install docker pytest

services:
  - docker

env:
  - NAME='latest' PYTHON_VERSION='3.10'
  - NAME='python3.10' PYTHON_VERSION='3.10'
  - NAME='python3.9' PYTHON_VERSION='3.9'
  - NAME='python3.8' PYTHON_VERSION='3.8'
  - NAME='python3.10-alpine3.16' PYTHON_VERSION='3.10'
  - NAME='python3.9-alpine3.14' PYTHON_VERSION='3.9'
  - NAME='python3.8-alpine3.10' PYTHON_VERSION='3.8'

script:
  - bash scripts/test.sh

jobs:
    include:
      - script: bash scripts/test.sh
      - stage: deploy
        script: skip
        deploy:
          provider: script
          script: bash scripts/build-push-all.sh
          on:
            branch: master
