name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        image:
          - name: latest
            python_version: "3.10"
          - name: python3.10
            python_version: "3.10"
          - name: python3.9
            python_version: "3.9"
          - name: python3.8
            python_version: "3.8"
          - name: python3.10-slim
            python_version: "3.10"
          - name: python3.9-slim
            python_version: "3.9"
          - name: python3.8-slim
            python_version: "3.8"
      fail-fast: true
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Install Dependencies
        run: python3.10 -m pip install "docker>=5.0.3" "pytest>=7.1.2"
      - name: Deploy Image
        run: bash scripts/build-push.sh
        env:
          NAME: ${{ matrix.image.name }}
          DOCKERFILE: ${{ matrix.image.dockerfile }}
          PYTHON_VERSION: ${{ matrix.image.python_version }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
